"""Upgrade themes table

Revision ID: 800ee7af4d09
Revises: fd5e2788127e
Create Date: 2024-04-20 12:23:58.265778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800ee7af4d09'
down_revision: Union[str, None] = 'fd5e2788127e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
